-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 06, 2025 at 02:58 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `timelines`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` int(10) NOT NULL,
  `img` varchar(255) NOT NULL,
  `categories_name` varchar(100) NOT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `img`, `categories_name`, `status`) VALUES
(1, 'img/children.png', 'Children', 'active'),
(2, 'img/menwatch.png', 'Men', 'active'),
(3, 'img/womenwatch.png', 'Women', 'active'),
(4, 'img/Antique.jpg', 'Antique', 'active'),
(5, 'img/smartwatch.png', 'Smart', 'active'),
(6, 'img/wallclock.jpg', 'Wall', 'active'),
(7, 'img/couplewatch.png', 'Couple', 'active');

-- --------------------------------------------------------

--
-- Table structure for table `crousel`
--

CREATE TABLE `crousel` (
  `id` int(11) NOT NULL,
  `img` varchar(255) NOT NULL,
  `title` varchar(100) NOT NULL,
  `dec` text NOT NULL,
  `button` varchar(30) NOT NULL,
  `stats` enum('active','inactive') NOT NULL DEFAULT 'active'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `crousel`
--

INSERT INTO `crousel` (`id`, `img`, `title`, `dec`, `button`, `stats`) VALUES
(1, 'img/apple_banner2.jpg', 'Smart Watches', 'Provide a Diffent type of Watch', 'Shop', 'active'),
(10, 'img/womenwatch.jpg', 'Luxery Women Watch', 'shop now luxery brands on TimeLines', 'Shop Now', 'active'),
(11, 'img/men_watch_benner.jpg', 'Mens Luxery Watch', 'shop luxery mens brands on timelines', 'Shop Now', 'active');

-- --------------------------------------------------------

--
-- Table structure for table `feed`
--

CREATE TABLE `feed` (
  `id` int(11) NOT NULL,
  `nm` varchar(100) NOT NULL,
  `email` varchar(50) NOT NULL,
  `subject` text NOT NULL,
  `message` text NOT NULL,
  `time` date NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `feed`
--

INSERT INTO `feed` (`id`, `nm`, `email`, `subject`, `message`, `time`) VALUES
(3, 'Dhrudip Timbaliya', 'dhrudip@gmail.com', 'hello', 'watch are the best ', '2025-09-19'),
(4, 'hi ', 'dhrudip@gmail.com', 'hello', 'watch brands best', '2025-09-19'),
(6, 'Dhrudip Timbaliya', 'dhrudip@gmail.com', 'heloo', 'best watch', '2025-09-24');

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

CREATE TABLE `orders` (
  `order_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `product_id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `address` text NOT NULL,
  `shipping` enum('standard','expressed') NOT NULL,
  `shipping_amt` int(11) NOT NULL,
  `tax` int(11) NOT NULL DEFAULT 0,
  `total` int(11) NOT NULL,
  `order_status` enum('Pending','Processing','Shipped','Delivered','Cancelled') NOT NULL DEFAULT 'Pending',
  `created_at` date NOT NULL DEFAULT current_timestamp(),
  `updated_at` date NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `orders`
--

INSERT INTO `orders` (`order_id`, `user_id`, `product_id`, `address`, `shipping`, `shipping_amt`, `tax`, `total`, `order_status`, `created_at`, `updated_at`) VALUES
(1, 1, '13', 'aadarsh avnu ,mavdi, rajkot, 360004, gujrat, india, Phone: 9328070359', 'expressed', 36, 700, 7725, 'Pending', '2025-08-24', '2025-08-24'),
(2, 1, '[{\"product_id\":\"17\",\"name\":\"boAt New Launch Ultima Ember Smartwatch w/ 1.96 (4.97 cm) AMOLED Display\",\"quantity\":2},{\"product_id\":\"15\",\"name\":\"Titan Zeal 1.85 AMOLED Metal Case Smart Watch\",\"quantity\":1}]', 'aadarsh avnu ,mavdi, rajkot, 360004, gujrat, india, Phone: 9328070359', 'standard', 0, 900, 9887, 'Processing', '2025-08-25', '2025-08-25'),
(3, 1, '[{\"product_id\":\"8\",\"name\":\"Noise Diva Smartwatch with Diamond Cut dial, Glossy Metallic Finish\",\"quantity\":1}]', 'aadarsh avnu ,mavdi, rajkot, 360004, gujrat, india, Phone: 9328070359', 'expressed', 36, 250, 2775, 'Pending', '2025-08-28', '2025-08-28'),
(4, 1, '[{\"product_id\":\"43\",\"name\":\"V2A Cute Analog Design Watch for Girl -Child Between 4 to 13 Years of Age\",\"quantity\":1}]', 'aadarsh avnu ,mavdi, rajkot, 360004, gujrat, india, Phone: 9328070359', 'standard', 0, 70, 759, 'Pending', '2025-09-09', '2025-09-09'),
(5, 1, '[{\"product_id\":\"61\",\"name\":\"Handcrafted Resin Art Wall Clock \",\"quantity\":1}]', 'aadarsh avnu ,mavdi, rajkot, 360004, gujrat, india, Phone: 9328070359', 'standard', 0, 210, 2299, 'Pending', '2025-09-21', '2025-09-21'),
(6, 1, '[{\"product_id\":\"44\",\"name\":\"V2A Boys and Girls Kids Watch - Waterproof Watch, Gifts for Boys and Girls Age 5-13\",\"quantity\":2},{\"product_id\":\"45\",\"name\":\"V2A Kids 3D Astronaut Print Digital Watch for Boys & Girls Aged 3 to 10\",\"quantity\":3}]', 'aadarsh avnu ,mavdi, rajkot, 360004, gujrat, india, Phone: 9328070359', 'standard', 0, 360, 3945, 'Pending', '2025-09-21', '2025-09-21'),
(7, 2, '[{\"product_id\":\"44\",\"name\":\"V2A Boys and Girls Kids Watch - Waterproof Watch, Gifts for Boys and Girls Age 5-13\",\"quantity\":2},{\"product_id\":\"45\",\"name\":\"V2A Kids 3D Astronaut Print Digital Watch for Boys & Girls Aged 3 to 10\",\"quantity\":3}]', ';ksqjfpojewfrqwoefhq3othuofhqwth1uot, qwdjlhduo, 36004, Gujrat, india, Phone: 6355669169', 'standard', 0, 360, 3945, 'Pending', '2025-09-21', '2025-09-21'),
(8, 1, '[{\"product_id\":\"30\",\"name\":\"NIBOSI Women Watches Analogue Wrist Watches\",\"quantity\":2}]', 'aadarsh avnu ,mavdi, rajkot, 360004, gujrat, india, Phone: 9328070359', 'standard', 0, 600, 6586, 'Processing', '2025-09-23', '2025-09-23'),
(9, 1, '[{\"product_id\":\"25\",\"name\":\"OLEVS Mens Business Watch Gold Blue with Large Easy-Read Analog Quartz\",\"quantity\":2},{\"product_id\":\"46\",\"name\":\"YouBella Pocket Watch Pendant with Chain\",\"quantity\":1}]', 'aadarsh avnu ,mavdi, rajkot, 360004, gujrat, india, Phone: 9328070359', 'standard', 0, 721, 7920, 'Pending', '2025-09-25', '2025-09-25');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(150) NOT NULL,
  `name` text NOT NULL,
  `price` decimal(20,2) NOT NULL,
  `img1` text NOT NULL,
  `img2` text NOT NULL,
  `img3` text NOT NULL,
  `img4` text NOT NULL,
  `quentity` int(11) NOT NULL,
  `category` varchar(100) NOT NULL,
  `brand_name` varchar(100) NOT NULL,
  `short_dec` text NOT NULL,
  `long_dec` text NOT NULL,
  `speci` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`speci`)),
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `trends` enum('yes','no') NOT NULL DEFAULT 'no',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `price`, `img1`, `img2`, `img3`, `img4`, `quentity`, `category`, `brand_name`, `short_dec`, `long_dec`, `speci`, `status`, `trends`, `created_at`, `updated_at`) VALUES
(4, 'boAt Enigma Gem Womens Luxury Smart Watch ', 2899.00, 'img/smart/boat_enidme_women_watch_luxery0.jpg', 'img/smart/boat_enidme_women_watch_luxery1.jpg', 'img/smart/boat_enidme_women_watch_luxery2.jpg', 'img/smart/boat_enidme_women_watch_luxery3.jpg', 30, 'Smart', 'boAt', 'w/ 1.19” (3.02cm) AMOLED Display, Emergency SOS Live Location Sharing, Watch Face Studio, QR Tray, BT Calling, 700+ Active Mode, HR & SpO2 (Metallic Black)', 'Emergency SOS with Live location sharing: You can send an SOS signal, when in distress, to your added emergency contact from this watch along with live location sharing with MapMyIndia.    1.19” Round AMOLED Display: Stay informed of the time, date, notifications, alerts, and more on the round 1.19” (3.02 cm) AMOLED display of the boAt Enigma Gem Smartwatch. Also, high resolution ensures that you can glance at the screen and get the info even in the daytime.Health and Female Wellness Features: Record vital health metrics, such as heartbeats per minute, blood oxygen levels (SpO2), sleep score, menstrual cycle, and more to monitor your fitness.', '{\"Operating System\":\"android & ios \",\"Special Feature\":\"IP67 Dust, Sweat, & Splash Resistance\",\"Connectivity Technology\":\"Bluetooth\",\"Wireless Communication Standard\":\"Bluetooth\",\"Battery Cell Composition\":\"Lithium Polymer\"}', 'active', 'yes', '2025-09-09 16:21:38', '2025-08-09 12:43:25'),
(5, 'boAt Lunar Vista w/Large 1.52', 1599.00, 'img/smart/boat_Lunar_Vista0.png', 'img/smart/boAt_Lunar_Vista1.jpg', 'img/smart/boAt_Lunar_Vista2.jpg', 'img/smart/boAt_Lunar_Vista3.jpg', 33, 'Smart', 'boAt', ' (3.8 cm) HD Always on Display,550 Nits Brightness, Functional Crown,100+ Sports Mode, Heart Rate & Sp02 Monitoring, Fitness Smart Watch for Men & Women(Active Black)', 'Screen Size: Experience a new level of visual immersion with the captivating 1.52\" (3.86 cm) HD Display making every glance a visual delight.\r\nAlways on Display: Always on Display allows you to view the home screen without having to repeatedly use the wake gesture. Please be aware that in this mode, the battery can last up to two days.\r\nFunctional Crown: Effortlessly navigate and interact with the smartwatch through the intuitive Functional Crown allowing for smooth control.', '{\" Operating System\":\"Smartwatch\",\"Special Feature\\t\":\"Functional Crown, 100+ Sports Modes, Always On Display\",\"Battery Capacity\":\"290 Milliamp Hours\",\"Connectivity Technology\":\"Bluetooth\",\"Wireless Communication Standard\":\"Bluetooth\"}', 'active', 'no', '2025-09-01 13:02:43', '2025-08-10 20:08:32'),
(6, 'Noise Pulse 4 Max Smart Watch', 2499.00, 'img/smart/Noise Pulse 4 Max Smart Watch1.jpg', 'img/smart/Noise Pulse 4 Max Smart Watch2.jpg', 'img/smart/Noise Pulse 4 Max Smart Watch3.jpg', 'img/smart/Noise Pulse 4 Max Smart Watch4.jpg', 35, 'Smart', 'Noise', 'with AI Create (India\'a 1st Ever with Unlimited Watch Faces), AI Search, 1.96\" AMOLED Display, Functional Crown, Premium Metallic Finish, Health Suite (Deep Wine)', 'AI Create: Turn your watch face into a canvas where your imagination runs wild.\r\nAI Search: Got questions? Just ask away and watch the answers pop up on your wrist, like magic!\r\n1.96” AMOLED display with AOD: A vibrant 1.96-inch display with an always-on feature for brilliant glances.\r\n', '{\" Operating System\":\"Smartwatch\",\"Special Feature\":\"Gesture Control, Lightweight, Alarm Clock, Activity Tracker, Notifications\",\"Connectivity Technology\":\"Bluetooth\",\"Wireless Communication Standard\":\"Bluetooth\",\"GPS\":\"No GPS\"}', 'active', 'no', '2025-09-01 13:02:58', '2025-08-10 20:42:42'),
(7, 'Noise Halo Plus 1.46 Super AMOLED Display Elite Smart Watch', 2999.00, 'img/smart/Noise Halo Plus1.jpg', 'img/smart/Noise Halo Plus2.jpg', 'img/smart/Noise Halo Plus3.jpg', 'img/smart/Noise Halo Plus4.jpg', 34, 'Smart', 'Noise', ' Bluetooth Calling, Stainless Steel Build, Always on Display, Upto 7 Days Battery (Elite Black)', '1.46 inches (3.7cms) AMOLED display, 466*466px, Always on display - Yes - Enjoy clear and immersive visuals on its round AMOLED display.\r\nUp to 7-day battery life - Get up to 7 days of battery life & up to 2 days of power with calling activated. (Battery life can vary due to multiple factors such as turning on continuous HR tracking or turning up the brightness)\r\nCharging - The smartwatch comes with a 300mAh battery that takes approx. 2 hours to fully charge. It is recommended that you use a 5W power adapter. Please avoid using a fast-charging adapter to prevent future watch damage.', '{\"Style Name\":\"Metal Strap\",\"Special Feature\":\"Activity Tracker, Calorie Tracker, Oxymeter (SpO2), Notifications, Heart Rate Monitor\",\"Battery Capacity\":\"300\",\" Connectivity Technology\":\"Bluetooth\",\"Wireless Communication Standard\":\"Bluetooth\",\"Battery Cell Composition\":\"Lithium Ion\"}', 'active', 'no', '2025-09-01 13:03:11', '2025-08-10 21:59:14'),
(8, 'Noise Diva Smartwatch with Diamond Cut dial, Glossy Metallic Finish', 2499.00, 'img/smart/Noise Diva Smartwatch1.jpg', 'img/smart/Noise Diva Smartwatch2.jpg', 'img/smart/Noise Diva Smartwatch3.jpg', 'img/smart/Noise Diva Smartwatch4.jpg', 37, 'Smart', 'Noise', 'AMOLED Display, Mesh Metal and Leather Strap Options, 100+ Watch Faces, Female Cycle Tracker Smart Watch for Women (Rose Pink)', 'Diamond-cut dial: Enhance your style with a diamond-cut dial that perfectly complements your glamorous lifestyle, adding a touch of sophistication to your everyday look.\r\nMultiple strap options: Celebrate your unique sense of style with meticulously designed metallic and leather straps, offering a wide array of options to match any occasion or outfit.\r\n1.1” AMOLED display -Ignite your senses with mesmerising visuals, illuminating every second of your life and providing a truly captivating experience at every glance. Always on display - yes', '{\"Special Feature\":\"Activity Tracker, Calorie Tracker, Oxymeter (SpO2), Notifications, Heart Rate Monitor\",\"Connectivity Technology\":\"Bluetooth\",\"Wireless Communication Standard\":\"Bluetooth\",\"GPS\":\"\\tNo GPS\",\"Shape\":\"Round\"}', 'active', 'yes', '2025-09-01 13:03:27', '2025-08-10 22:35:47'),
(9, 'Fastrack Limitless Glide X 1.83 Smart Watch with Ultra UV HD Display,', 1499.00, 'img/smart/Fastrack Limitless Glide1.jpg', 'img/smart/Fastrack Limitless Glide2.jpg', 'img/smart/Fastrack Limitless Glide3.jpg', 'img/smart/Fastrack Limitless Glide4.jpg', 37, 'Smart', 'Fastrack ', 'SpO2, Heart Rate & Sleep Tracking, Bluetooth Calling, 100+ Sports Modes, 5-Day Battery, Smartwatch for Men & Women (Blue)\r\nVisit the Fastrack Store\r\n500+ bought in past month', '1.83” Large Display With 450 Nits Brightness - This smart watch features a 1.83\" vivid display with 240×286 resolution, 203 PPI sharpness, and panda glass for clear visibility indoors and outdoors—perfect for men and women\r\nBluetooth Calling & Seamless Controls - Answer or mute calls directly from your smartwatch with single-sync Bluetooth calling. Enjoy music & camera control, find phone, alarm, and calculator features—ideal smart watch for man & woman.\r\n100+ Sports Modes & Fitness Features - Track 100+ sports and fitness activities including walking, running, yoga, and more. Customize with 100+ watch faces—perfect smartwatch for woman, man, or teens looking to stay active.', '{\"Operating System\":\"Android Wear 2.9\",\"Memory Storage Capacity\":\"16 MB\",\"Special Feature\":\"Multisport Tracker, Activity Tracker, Phone Call, Stress Tracking, Heart Rate Monitor\",\"Battery Capacity\\t\":\"280\",\"Connectivity Technology\\t\":\"Bluetooth\"}', 'active', 'no', '2025-09-01 13:03:42', '2025-08-11 21:36:13'),
(10, 'Titan Heritage 1.43 AMOLED Stainless Steel Bracelet Smart Watch', 12499.00, 'img/smart/Titan Heritage1.jpg', 'img/smart/Titan Heritage2.jpg', 'img/smart/Titan Heritage3.jpg', 'img/smart/Titan Heritage4.jpg', 32, 'Smart', 'Titan', 'for Men, BT Calling, Voice Assistant, Quick Health Measurement, Functional Crown, 3D UI, 60Hz Display, Fast Charging (Blue)', 'Celebrating tradition and legacy – With heritage-inspired design, bold 1.43” AMOLED display (466x466 resolution, 60Hz refresh rate, 750 nits brightness), and an unmatched balance of smart technology, this smartwatch for men exudes class. All-SS 46mm case, rotary crown & haptic feedback.\r\nPowerful, Smooth & Personalized UI – Next-gen ATS chipset with fully animated UI, 3D watch faces, 1GB RAM, custom hotkey, multiple menu styles & themes—smartwatch for man built for precision and style.\r\nBluetooth Calling & Smart Control Hub –SingleSync BT 5.3, AI voice assistant, call mute, quick reply (Android), music/camera control, find phone, calendar & notifications—watch for man smartwatch with smart features.', '{\" Operating System\":\"android\",\"Special Feature\":\"Activity Tracker, Phone Call\",\"Battery Capacity\":\"350 Milliamp Hours\",\"Connectivity Technology\":\"Bluetooth\",\"Wireless Communication Standard\":\"Bluetooth\"}', 'active', 'no', '2025-09-01 13:03:56', '2025-08-11 22:06:05'),
(11, 'Fastrack Jupitor R2 Smart Watch, 1.38 TFT Display, 240 * 240 Pixel Resolution', 1799.00, 'img/smart/Fastrack Jupitor1.jpg', 'img/smart/Fastrack Jupitor2.jpg', 'img/smart/Fastrack Jupitor3.jpg', 'img/smart/Fastrack Jupitor4.jpg', 45, 'Smart', 'Fastrack ', ', SingleSync BT Calling, AI Voice Assistant, 100+ Sports Modes & Smartwatch Faces,Upto 5 Day Battery, IP68 (Blue)', 'Enjoy a vibrant 1.38” display with 500 nits brightness and metallic bezel. A premium pick among smart watches for men, women, girls, and kids.\r\nStay connected with Single Sync BT calling. Make calls, access logs, save contacts—navigate easily with the crown. Ideal smart watch for men latest and smart watch for women.', '{\" Operating System\":\"Smartwatch\",\"Special Feature\":\"Multisport Tracker, Activity Tracker, Phone Call, Stress Tracking, Heart Rate Monitor\",\"Connectivity Technology\":\"Bluetooth\",\"Wireless Communication Standard\\t\":\"Bluetooth\",\"Battery Cell Composition\\t\":\"Lithium Ion\"}', 'active', 'no', '2025-09-01 13:04:10', '2025-08-11 22:18:48'),
(12, 'Noise Pro 6 Smart Watch Intelligent AI, Endless AI Watch Faces, AI Companion, 1.85 AMOLED,', 6498.00, 'img/smart/Noise Pro 6 Smart Watch1.jpg', 'img/smart/Noise Pro 6 Smart Watch2.jpg', 'img/smart/Noise Pro 6 Smart Watch3.jpg', 'img/smart/Noise Pro 6 Smart Watch4.jpg', 39, 'Smart', 'Noise', 'EN2 Processor, Nebula UI 2.0, Emergency SOS, Compatible with iOS & Android (Arctic Weave), Multicolor', 'AI-Driven Watchfaces: Dynamic and intelligent watchfaces that adapt to your style and preferences.\r\nAI Companion for Fitness & Wellness: Offers personalized insights and recommendations tailored to your health and wellness goals.\r\nPowered by EN 2 Processor: Enhanced performance with the advanced EN 2 processor for seamless operation.', '{\" Operating System\":\"android,ios\",\"Special Feature\":\"Activity Tracker, Alarm Clock, Lightweight, Notifications, Touchscreen\",\"Connectivity Technology\":\"Bluetooth\",\"Wireless Communication Standard\":\"Bluetooth\",\" GPS\":\"  No GPS\"}', 'active', 'yes', '2025-09-01 13:04:28', '2025-08-14 14:52:43'),
(13, 'Titan Evolution Smart Watch, 1.85  AMOLED Display, 390 * 450 Pixel Resolution', 6999.00, 'img/Smart/Titan Evolution Smart Watch1.jpg', 'img/Smart/Titan Evolution Smart Watch2.jpg', 'img/Smart/Titan Evolution Smart Watch3.jpg', 'img/Smart/Titan Evolution Smart Watch4.jpg', 40, 'Smart', 'Titan', ' SingleSync BT Calling, AI Voice Assistant, 100+ Sports Modes & Smartwatch Faces, Upto 7 Day Battery, IP68 (Black)', 'Titan Evolution comes with 1.85” AMOLED Display with 390*450 Pixel Resolution\r\nSingleSync BT Calling with functional crown , 100+ Sports Mode and Watchfaces\r\nAll-Round Health Tracking,Up to 7 day battery, IP68 Water Resistance and many more handy features at a single tap\r\nHealth Monitoring with Stress monitor, 24x7 HRM, SPO2', '{\"Operating System\":\"Smartwatch\",\"Special Feature\":\"Activity Tracker, Heart Rate Monitor, Multisport Tracker, Phone Call, Stress Tracking\",\"Connectivity Technology\":\"Bluetooth\",\"Wireless Communication Standard\":\"Bluetooth\",\"Battery Cell Composition\":\"Lithium Polymer\"}', 'active', 'no', '2025-08-29 07:57:28', '2025-08-21 18:13:55'),
(14, 'Noise Ultra 3 Luminary with India 1st Ever Personalised Notification Alerts (Lumilert),', 2999.00, 'img/Smart/Noise Ultra 3 Luminary1.jpg', 'img/Smart/Noise Ultra 3 Luminary2.jpg', 'img/Smart/Noise Ultra 3 Luminary3.jpg', 'img/Smart/Noise Ultra 3 Luminary4.jpg', 39, 'Smart', 'Noise', '1.96\" AMOLED Display, Premium Metallic Dial, Send Upto 5 Emojis (Lumiping), Health Suite (Jet Black)', 'Lumilert: Stay in the loop and never miss a beat with personalised notification alerts on your smartwatch.\r\nLumiping: Spark up your conversations and say it all with emojis with a tap on your watch.\r\n1.96” AMOLED display with AOD: Watch your world in vivid detail with a stunning display and always-on feature.', '{\" Operating System\":\"Smartwatch\",\"Special Feature\":\"Activity Tracker, Alarm Clock, Gesture Control, Lightweight, Notifications\",\"Connectivity Technology\":\"Bluetooth\",\"Wireless Communication Standard\":\"Bluetooth\",\"GPS\":\"No GPS\"}', 'active', 'no', '2025-09-09 16:20:38', '2025-08-24 20:51:00'),
(15, 'Titan Zeal 1.85 AMOLED Metal Case Smart Watch', 3999.00, 'img/Smart/Titan Zeal1.jpg', 'img/Smart/Titan Zeal2.jpg', 'img/Smart/Titan Zeal3.jpg', 'img/Smart/Titan Zeal4.jpg', 36, 'Smart', 'Titan', ' with BT Calling, SpO2, 100+ Sports Modes, Auto Sports Recognition, Fast Charging Smartwatch for Men & Women with – Black Mesh Metal Strap (Rose Gold)', 'Big, Bright AMOLED Display with Premium Build - Enjoy a vibrant 1.85\" AMOLED screen with 600 nits brightness for easy outdoor viewing. Encased in a sleek aluminium body and tough Panda Glass for a stylish yet durable finish.\r\nAdvanced Health Monitoring, 24x7 - Track SpO2, continuous heart rate, sleep (including REM and naps), stress, and women’s wellness. Includes hydration reminders, sedentary alerts, and breathing exercises for all-round health.\r\n100+ Sports Modes with Auto Recognition - Stay fit with 100+ multi-sports tracking and automatic detection of workouts. Powered by AI Coach and My Fitness to help you meet your goals with smart insights and personalized feedback.', '{\"Operating System\":\"android\",\"Special Feature\":\"Activity Tracker, Heart Rate Monitor, Multisport Tracker, Phone Call, Stress Tracking\",\"Battery Capacity\":\"300\",\"Connectivity Technology\":\"Bluetooth\",\"Wireless Communication Standard\":\"Bluetooth\"}', 'active', 'no', '2025-08-29 07:58:14', '2025-08-24 21:18:04'),
(16, 'Fastrack Astor FR2 Pro 1.43 AMOLED Stainless Steel Smart Watch', 2999.00, 'img/Smart/Fastrack Astor FR2 Pro1.jpg', 'img/Smart/Fastrack Astor FR2 Pro2.jpg', 'img/Smart/Fastrack Astor FR2 Pro3.jpg', 'img/Smart/Fastrack Astor FR2 Pro4.jpg', 45, 'Smart', 'Fastrack', 'with SpO2, Heart Rate, BT Calling, Adaptive AOD, Functional Crown, AI Voice Assistant – Smartwatch for Stylish Professionals (Black)', 'Stylish Design Meets Smart Tech – A sleek smartwatch for man or woman with a 1.43” AMOLED display, premium metal build, and adaptive always-on screen. Designed for those who want their smart watch to double as a fashion statement.\r\nSmart Calling, Smarter Living – Take calls from your wrist with SingleSync Bluetooth Calling. A must-have feature for professionals looking for a digital watch for man or women that keeps them effortlessly connected.\r\nSmooth Navigation, Maximum Control – Functional crown and dual menu styles ensure seamless interaction. Whether you\'re wearing a watch for man smartwatch or wrist watch for woman, control is always at your fingertips.', '{\"Operating System\":\"android\",\"Special Feature\":\"Activity Tracker, Heart Rate Monitor, Multisport Tracker, Phone Call, Stress Tracking\",\"Battery Capacity\":\"5\",\"Connectivity Technology\\t\":\"Bluetooth\",\"Wireless Communication Standard\\t\":\"Bluetooth\"}', 'active', 'no', '2025-08-29 07:59:02', '2025-08-24 21:48:17'),
(17, 'boAt New Launch Ultima Ember Smartwatch w/ 1.96  (4.97 cm) AMOLED Display', 2499.00, 'img/Smart/boAt New Launch1.jpg', 'img/Smart/boAt New Launch2.jpg', 'img/Smart/boAt New Launch3.jpg', 'img/Smart/boAt New Launch4.jpg', 46, 'Smart', 'boAt', ', Personalized Fitness Nudges, Functional Crown, 100+ Sports Modes, Custom Watch Faces (Steel Black)', '1.96” (4.97 cm) AMOLED Display: Experience a crystal-clear view on the 1.96” (4.97 cm) AMOLED display of the boAt Ultima Ember Smartwatch. With a 368x448p resolution and Always on Display, it makes checking the time, notifications, vital stats, and more effortless.\r\nFunctional Crown: Navigate through the options on the menu, scroll through notifications, and control other features effortlessly with the functional crown.', '{\"Operating System\\t\":\"android\",\"Special Feature\\t\":\"Voice Assistant, Bluetooth Calling, Multisport Tracker, Advanced Health Tracking\",\"Connectivity Technology\\t\":\"Bluetooth\",\"Wireless Communication Standard\\t\":\"Bluetooth\",\"Battery Cell Composition\\t\":\"Lithium Polymer\"}', 'active', 'no', '2025-08-29 07:59:23', '2025-08-24 21:57:44'),
(18, 'Daniel Hechter Paris Rivoli Collection Modern Analog Watch for Men', 2499.00, 'img/Men/Daniel Hechter Paris Rivoli1.jpg', 'img/Men/Daniel Hechter Paris Rivoli2.jpg', 'img/Men/Daniel Hechter Paris Rivoli3.jpg', 'img/Men/Daniel Hechter Paris Rivoli4.jpg', 50, 'Men', 'Daniel Hechter', 'with Octagon Dial and Silicon Band-DHM1003', 'Brand & Design: Daniel Hechter Paris men\'s chronograph watch with a modern cushion-shaped black stainless steel case.\r\nMultifunctional Features: Chronograph with three subdials for stopwatch functionality and date display window.\r\nPremium Quality: Durable black silicone strap offering comfort and long-lasting wear.', '{\"Case diameter\":\"42 Millimetres\",\"Band colour\":\"Black\",\"Band material type\":\"Silicone\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"250 Grams\",\"Country of Origin\":\"Hong Kong\"}', 'active', 'no', '2025-09-01 11:46:02', '2025-09-01 17:16:02'),
(19, 'Daniel Hechter Paris Clichy Collection Sporty Watch for Men with Two-Tone Bezel', 2495.00, 'img/Men/Daniel Hechter Paris Clichy1.jpg', 'img/Men/Daniel Hechter Paris Clichy2.jpg', 'img/Men/Daniel Hechter Paris Clichy3.jpg', 'img/Men/Daniel Hechter Paris Clichy4.jpg', 55, 'Men', 'Daniel Hechter', ', Stainless Steel Strap, Luminous Hands, Date Function-DHM1013', 'Strap: Comfortable and durable stainless steel strap with a secure deployment clasp\r\nMovement: Quartz movement for reliable and accurate performance\r\nPrecision Chronograph Movement: Offers accurate timekeeping with multiple sub-dials for added functionality', '{\"Case diameter\":\"33 Millimetres\",\"Band colour\":\"Black\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"350 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-01 12:15:38', '2025-09-01 17:45:38'),
(20, 'Daniel Hechter Paris Bercy Collection Modern Multi Functional Watch for Men', 2699.00, 'img/Men/Daniel Hechter Paris Bercy1.jpg', 'img/Men/Daniel Hechter Paris Bercy2.jpg', 'img/Men/Daniel Hechter Paris Bercy3.jpg', 'img/Men/Daniel Hechter Paris Bercy4.jpg', 52, 'Men', 'Daniel Hechter', ' with Square Dial and Silicon Band-DHM1001', 'Brand & Design: Daniel Hechter Paris men\'s chronograph watch with a modern cushion-shaped black stainless steel case.\r\nMultifunctional Features: Chronograph with three subdials for stopwatch functionality and date display window.\r\nPremium Quality: Durable black silicone strap offering comfort and long-lasting wear.', '{\"Case diameter\":\"42 Millimetres\",\"Band colour\":\"Green\",\"Band material type\":\"Silicone\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"250 Grams\",\"Country of Origin\":\"India\"}', 'active', 'yes', '2025-09-02 12:51:20', '2025-09-01 17:53:15'),
(21, 'Daniel Hechter Paris Bastille Collection Analog Watch for Men', 2450.00, 'img/Men/Daniel Hechter Paris Bastille1.jpg', 'img/Men/Daniel Hechter Paris Bastille2.jpg', 'img/Men/Daniel Hechter Paris Bastille3.jpg', 'img/Men/Daniel Hechter Paris Bastille4.jpg', 53, 'Men', 'Daniel Hechter', 'with Round Dial, Stainless Steel Strap and Date Function-DHM1014', 'Strap: Comfortable and durable rubber strap with a secure buckle closure\r\nMovement: Quartz movement for reliable and accurate performance\r\nPrecision Chronograph Movement: Offers accurate timekeeping with multiple sub-dials for added functionality.', '{\"Case diameter\":\"34 Millimetres\",\"Band colour\":\"Black\",\"Band material type\":\"Silicone\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"350 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-01 12:53:08', '2025-09-01 18:23:08'),
(22, 'Artisans Alley Wall Clock Decor Art Sculpture', 1775.00, 'img/Wall/Artisans Alley Wall Clock Decor Art.jpg', 'img/Wall/Artisans Alley Wall Clock Decor Art1.jpg', 'img/Wall/Artisans Alley Wall Clock Decor Art2.jpg', 'img/Wall/Artisans Alley Wall Clock Decor Art3.jpg', 50, 'Wall', 'Artisans Alley', 'for Home Office Living Room Bedroom Restaurant Cafe (24 Inches/ 60 Cms) (Black and Gold)', '', '{\"Brand\":\"Generic\",\"Colour\":\"Black and Gold\",\"Display Type\":\"Analog\",\"Style\":\"WC-36\",\"Special Feature\":\"Silent Clock\",\"Product Dimensions\":\"40W x 60H Centimeters\",\"Power Source\":\"Battery Powered\",\"Age Range (Description)\":\"All Ages\",\"Room Type\":\"Office, Restaurant, Living Room, Bedroom, Dining Room\",\"Shape\":\"feather\"}', 'active', 'no', '2025-09-26 12:39:45', '2025-09-03 18:16:16'),
(23, 'OLEVS Original Mens Diamond Watch Analog Quartz Stainless Steel', 3229.00, 'img/Men/OLEVS Original Men\'s Diamond Watch2.jpg', 'img/Men/OLEVS Original Men\'s Diamond Watch1.jpg', 'img/Men/OLEVS Original Men\'s Diamond Watch3.jpg', 'img/Men/OLEVS Original Men\'s Diamond Watch4.jpg', 55, 'Men', 'OLEVS', 'Calendar Business Dress Watch with Luminous Waterproof Casual Wristwatch', '⌚OLEVS Original Watch for Men: This watches feature a high-quality quartz movement, ensuring precise timekeeping. Perfect for busy meetings or weekend outings, it helps you stay efficient and composed. The finely polished strap is comfortable for all-day wear.\r\n⌚Analog Quartz Mens Watch: With a simple and elegant design, this watch suits any occasion. Whether paired with a suit or casual wear, it adds a touch of sophistication to your style, blending luxury with understated charm.', '{\"Case diameter\":\"41 Millimetres\",\"Band colour\":\"Two tone\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"150 Grams\",\"Country of Origin\":\"China\"}', 'active', 'no', '2025-09-09 16:19:30', '2025-09-04 13:45:24'),
(24, 'OLEVS Multifunctional Chronograph Calendar Watch for Man', 3420.00, 'img/Men/OLEVS Multifunctional Chronograph2.jpg', 'img/Men/OLEVS Multifunctional Chronograph1.jpg', 'img/Men/OLEVS Multifunctional Chronograph3.jpg', 'img/Men/OLEVS Multifunctional Chronograph4.jpg', 56, 'Men', 'OLEVS', 'Diamond Analog Moon Phases Wrist Watches Stainless Steel Waterproof Luminous Mens Watch', '⌚Fashion Design Men Watch: Built from high-quality stainless steel, this men watch resists scratches so it looks as good as new for years. The watch face has a ripple texture and simple, clear markers that give it an elegant look. The bezel has a smooth blue-to-red color transition with gold accents, creating a striking appearance that balances elegance with vibrant energy. It enhances your personal style in both everyday and professional settings.', '{\"Case diameter\":\"41 Millimetres\",\"Band colour\":\"Silver\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"85 Grams\",\"Country of Origin\":\"China\"}', 'active', 'no', '2025-09-04 08:27:35', '2025-09-04 13:57:35'),
(25, 'OLEVS Mens Business Watch Gold Blue with Large Easy-Read Analog Quartz', 3417.00, 'img/Men/OLEVS Men\'s Business Watch1.jpg', 'img/Men/OLEVS Men\'s Business Watch2.jpg', 'img/Men/OLEVS Men\'s Business Watch3.jpg', 'img/Men/OLEVS Men\'s Business Watch4.jpg', 55, 'Men', 'OLEVS ', 'Date Display Luxury Stainless Steel Band Waterproof Luminous Hands', '⌚Perfect Gift for Men:This elegant watch makes a thoughtful and surprising gift for dads, husbands, boyfriends, and loved ones. Perfect for occasions like Christmas, Valentine\'s Day, Father\'s Day, Thanksgiving, anniversaries, birthdays, or any special event where you want to show someone how much you care.', '{\"Case diameter\":\"41 Millimetres\",\"Band colour\":\"Two tone\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"85 Grams\",\"Country of Origin\":\"China\"}', 'active', 'no', '2025-09-25 03:00:54', '2025-09-04 14:08:24'),
(26, 'Fossil Bannon Analog Green Dial Mens Watch-BQ2492', 11197.00, 'img/Men/Fossil Bannon Analog1.jpg', 'img/Men/Fossil Bannon Analog2.jpg', 'img/Men/Fossil Bannon Analog3.jpg', 'img/Men/Fossil Bannon Analog4.jpg', 47, 'Men', 'Fossil', '', 'Manufacturer-->Fossil, Fossil India Pvt Ltd Khata Khatoni No-147/150 Min, Village-Tipra Barotiwala Teh- Nalagarh Distt.-Solan (H.P) - 174103 |||\r\nPacker-->Fossil India Pvt. Ltd., Khasra No: 2058/1754/18 & 2059/1754/18, Waka Mouza Bhatoli kalan, Baddi 173205 India', '{\"Case diameter\":\"45 Millimetres\",\"Band colour\":\"Silver\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"120 Grams\",\"Country of Origin\":\"China\"}', 'active', 'no', '2025-09-09 16:17:59', '2025-09-04 22:18:10'),
(27, 'Fossil Men Leather Bronson Analog Black Dial Watch-Me3219, Band Color-Brown', 20995.00, 'img/Men/Fossil Men Leather Bronson.jpg', 'img/Men/Fossil Men Leather Bronson2.jpg', 'img/Men/Fossil Men Leather Bronson3.jpg', 'img/Men/Fossil Men Leather Bronson4.jpg', 57, 'Men', 'Fossil', '', 'Water resistant to 165 feet (50 M): suitable for short periods of exposure to water i.e washing hands or showering/bathing. Not suitable for recreational swimming, diving or snorkeling. Circumference - 200+/- 5MM\r\nWarranty type:Manufacturer; 2 Years Warranty', '{\"Brand\\t\":\"Fossil\",\"Manufacturer\\t\":\"\\u200eFossil India Pvt Ltd, Fossil India Pvt Ltd Khata Khatoni No-147\\/150 Min, Village-Tipra Barotiwala Teh- Nalagarh Distt.-Solan (H.P) - 174103\",\"Model\\t\":\"\\u200eME3219\",\"Model Name\\t\":\"\\u200eBronson\",\"Product Dimensions\\t\":\"\\u200e4.4 x 2.2 x 1.4 cm; 100 g\",\"Item model number\\t\":\"\\u200eME3219\",\"Special Features\\t\":\"\\u200eChronograph, Second Hand\"}', 'active', 'no', '2025-09-04 16:56:27', '2025-09-04 22:26:27'),
(28, 'Fossil Men Leather Townsman Analog Black Dial Watch', 19995.00, 'img/Men/Fossil Men Leather Townsman1.jpg', 'img/Men/Fossil Men Leather Townsman2.jpg', 'img/Men/Fossil Men Leather Townsman3.jpg', 'img/Men/Fossil Men Leather Townsman4.jpg', 56, 'Men', 'Fossil', '-Me3155, Brown, Free Size, Band Color-Brown', 'Packer-->>	Fossil India Pvt. Ltd., Khasra No: 2058/1754/18 & 2059/1754/18, Waka Mouza Bhatoli kalan, Baddi 173205 India\r\nImporter--->>	Fossil India Pvt. Ltd., Khasra No: 2058/1754/18 & 2059/1754/18, Waka Mouza Bhatoli kalan, Baddi 173205 India', '{\"Brand\":\"Fossil\",\"Manufacturer\":\"\\u200eFOSSIL INDIA PVT LTD, Fossil India Pvt Ltd Khata Khatoni No-147\\/150 Min, Village-Tipra Barotiwala Teh- Nalagarh Distt.-Solan (H.P) - 174103\",\"Model\":\"\\u200eME3155\",\"Model Name\\t\":\"Townsman\",\"Model Year\\t\":\"2017\",\"Product Dimensions\\t\":\"\\u200e4.8 x 2.4 x 1.2 cm; 100 g\",\"Batteries\":\"\\u200e1 9V batteries required. (included)\"}', 'active', 'no', '2025-09-04 17:08:34', '2025-09-04 22:38:34'),
(29, 'NIBOSI Women Stainless Steel Watches Analog Rose Gold Band', 2995.00, 'img/Women/NIBOSI Women Stainless Steel1.jpg', 'img/Women/NIBOSI Women Stainless Steel2.jpg', 'img/Women/NIBOSI Women Stainless Steel3.jpg', 'img/Women/NIBOSI Women Stainless Steel4.jpg', 56, 'Women', 'NIBOSI', 'and Square Dial Women\'s Watch for Girls&Miss&Ladies Diamond Studded with Stylish Watches Waterproof', '💎 Rock-solid quality: imported quartz movement to provide high stability and accurate timing. Stainless steel case with mineral glass, which greatly improves the wear resistance and scratch resistance. The Rose gold strap not only looks elegant and stylish, but is also comfortable and soft to wear.\r\n💎 Water Resistance: With a 3ATM (100 feet) rating, NIBOSI emerald green dial ladies wrist watch is water resistant up to 30 meters, making it suitable for daily activities such as accidental rain, hand washing, or splashing. However, it is not suitable for swimming, diving, or showering.', '{\"Case diameter\":\"31 Millimetres\",\"Band colour\":\"Rose Gold\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Contact Seller of Record\",\"Watch movement type\":\"Japanese Quartz\",\"Item weight\":\"62 Grams\",\"Country of Origin\":\"China\"}', 'active', 'no', '2025-09-07 06:24:04', '2025-09-07 11:54:04'),
(30, 'NIBOSI Women Watches Analogue Wrist Watches', 2998.00, 'img/Women/NIBOSI Women Watches Analogue3.jpg', 'img/Women/NIBOSI Women Watches Analogue1.jpg', 'img/Women/NIBOSI Women Watches Analogue2.jpg', 'img/Women/NIBOSI Women Watches Analogue4.jpg', 55, 'Women', 'NIBOSI ', 'Watches for Women\'s & Girls&Miss&Ladies Rose Gold Dial Watch with Stylish Diamond', ' Rock-solid quality: imported quartz movement to provide high stability and accurate timing. Stainless steel case with mineral glass, which greatly improves the wear resistance and scratch resistance. The Rose gold strap not only looks elegant and stylish, but is also comfortable and soft to wear.\r\nWater Resistance: With a 3ATM (100 feet) rating, NIBOSI rose gold dial ladies wrist watch is water resistant up to 30 meters, making it suitable for daily activities such as accidental rain, hand washing, or splashing. However, it is not suitable for swimming, diving, or showering.', '{\"Case diameter\":\"32 Millimetres\",\"Band colour\":\"Silver\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Contact Seller of Record\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"93 Grams\",\"Country of Origin\":\"China\"}', 'active', 'no', '2025-09-23 07:28:31', '2025-09-07 12:02:11'),
(31, 'Giordano Modern Analog Watch for Women', 3999.00, 'img/Women/Giordano Modern Analog Watch1.jpg', 'img/Women/Giordano Modern Analog Watch2.jpg', 'img/Women/Giordano Modern Analog Watch3.jpg', 'img/Women/Giordano Modern Analog Watch4.jpg', 55, 'Women', 'Giordano', '– Sleek Dial with Unique Chain-Link Bracelet and Stylish Stainless Steel Strap', 'Stylish Chain-Link Bracelet – Eye-catching chain-link design on the strap adds a modern twist to the traditional bracelet, perfect for fashion-forward individuals.\r\nPremium Plating – Crafted with a luxurious finish, this watch offers a radiant and sophisticated look suitable for any wardrobe.', '{\"Case diameter\":\"33 Millimetres\",\"Band colour\":\"Rose Gold\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"200 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-07 06:47:20', '2025-09-07 12:17:20'),
(32, 'Giordano Luxury Watch for Women', 2999.00, 'img/Women/Giordano Luxury Watch1.jpg', 'img/Women/Giordano Luxury Watch2.jpg', 'img/Women/Giordano Luxury Watch3.jpg', 'img/Women/Giordano Luxury Watch4.jpg', 58, 'Women', 'Giordano ', '– Round Diamond Cut Glass Dial, Elegant Stainless Steel Strap with Quartz Movement\r\n', 'Luxurious Diamond-Studded Dial – Features a stunning round dial embellished with sparkling diamond accents for a sophisticated and elegant look.\r\nDurable Stainless Steel Strap – Crafted from premium stainless steel, offering a sleek finish, long-lasting durability, and a comfortable fit.\r\nPrecision Quartz Movement – Equipped with a high-quality quartz mechanism to ensure accurate and reliable timekeeping.', '{\"Case diameter\":\"32 Millimetres\",\"Band colour\":\"Rose Gold\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"350 Grams\",\"Country of Origin\":\"India\"}', 'active', 'yes', '2025-09-18 11:45:55', '2025-09-07 12:36:10'),
(33, 'Giordano Analog Stylish Watch for Women', 2699.00, 'img/Women/Giordano Analog Stylish1.jpg', 'img/Women/Giordano Analog Stylish2.jpg', 'img/Women/Giordano Analog Stylish3.jpg', 'img/Women/Giordano Analog Stylish4.jpg', 56, 'Women', 'Giordano  ', 'with Mesh Metal Strap, 3 Hand Mechanism and Roman Numerals', 'Design: Elegant rectangular dial with a refined finish. The multifunctional layout includes sub-dials for day and date, providing both style and practicality.\r\nWatch Movement Type : Quartz, Watch Display Type : Analog/Multi-Function\r\nReflecting the dynamism of modern lifestyles, this men\'s analog watch from Giordano will be a great addition to your accessory collection', '{\"Case diameter\":\"35 Millimetres\",\"Band colour\":\"Brown\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"250 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-07 07:15:41', '2025-09-07 12:45:41'),
(34, 'Giordano Analog Stylish | Trendy Watch for Womens Water Resistant with Crystal Studded Dial', 2499.00, 'img/Women/Giordano Analog Stylish Trendy1.jpg', 'img/Women/Giordano Analog Stylish Trendy2.jpg', 'img/Women/Giordano Analog Stylish Trendy3.jpg', 'img/Women/Giordano Analog Stylish Trendy4.jpg', 58, 'Women', 'Giordano ', 'and Unique Design Metal Strap Wrist Watch to Compliment Your Look|Ideal Gift for Women|Ladies|Girls - C2196', 'and Unique Design Metal Strap Wrist Watch to Compliment Your Look|Ideal Gift for Women|Ladies|Girls - C2196', '{\"Case diameter \":\"40 Millimetres\",\"Band colour\":\"Rose Gold\",\"Band material type\":\"Metal\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"120 Grams\",\"Country of Origin\":\"Hong Kong\"}', 'active', 'no', '2025-09-09 16:17:09', '2025-09-07 13:00:55'),
(35, 'IMPERIOUS - THE ROYAL WAY Analogue Womens Watch (Black Dial)', 739.00, 'img/Women/IMPERIOUS - THE ROYAL WAY Women1.jpg', 'img/Women/IMPERIOUS - THE ROYAL WAY Women2.jpg', 'img/Women/IMPERIOUS - THE ROYAL WAY Women3.jpg', 'img/Women/IMPERIOUS - THE ROYAL WAY Women4.jpg', 60, 'Women', 'IMPERIOUS', '', 'Superior Quality : Imperious women watches are always stylish. Made from polished stainless steel. Simple design, clasp closure, lightweight, ensure you feel comfortable to wear. With the buckle closure, you don\'t have to worry about it falling off.\r\nSplash Resistance (Not Water Proof) :Feel free to use this stylish wrist watch while hand wash & drizzle as it is splash proof.', '{\"Case diameter\":\"38 Millimetres\",\"Band colour\":\"Black\",\"Band material type\":\"Metal\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"150 Grams\"}', 'active', 'no', '2025-09-09 16:16:29', '2025-09-07 14:10:42'),
(36, 'Imperious Wrist Watches for Women Stylist', 680.00, 'img/Women/Imperious Wrist Watches for Women1.jpg', 'img/Women/Imperious Wrist Watches for Women2.jpg', 'img/Women/Imperious Wrist Watches for Women3.jpg', 'img/Women/Imperious Wrist Watches for Women4.jpg', 55, 'Women', 'Imperious', '– Branded White Analogue Ladies Wrist Watch Dial – Silver Color Strap Watch', 'Superior Quality : Imperious women watches are always stylish. Made from polished stainless steel. Simple design, clasp closure, lightweight, ensure you feel comfortable to wear. With the buckle closure, you don\'t have to worry about it falling off.\r\nSplash Resistance (Not Water Proof) :Feel free to use this stylish wrist watch while hand wash & drizzle as it is splash proof.', '{\"Case diameter\":\"10 Centimetres\",\"Band colour\":\"Black\",\"Band material type\":\"Metal\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Automatic\",\"Case thickness\":\"7.5 Centimetres\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-07 08:51:30', '2025-09-07 14:21:30'),
(37, 'IMPEROUS - The Royal Way Womens Round Dial Watch', 657.00, 'img/Women/IMPEROUS - The Royal Way1.jpg', 'img/Women/IMPEROUS - The Royal Way2.jpg', 'img/Women/IMPEROUS - The Royal Way3.jpg', 'img/Women/IMPEROUS - The Royal Way4.jpg', 57, 'Women', 'IMPERIOUS ', '| Quartz Movement | Elegant Metal Strap | Slim Design', 'Elegant Design: Slim 8mm case thickness and 34mm case diameter for a refined look.\r\nQuartz Movement: Offers precise and reliable timekeeping.\r\nStylish Metal Strap: 15mm wide strap, providing both durability and elegance', '{\"Case diameter\":\"34 Millimetres\",\"Band colour\":\"Black\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"72 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-09 16:15:51', '2025-09-07 14:31:53'),
(38, 'IMPERIOUS - THE ROYAL WAY Womens Round Dial Quartz Movement Studded Dial Watch', 562.00, 'img/Women/IMPERIOUS - THE ROYAL WAY Women\'s Round Dial1.jpg', 'img/Women/IMPERIOUS - THE ROYAL WAY Women\'s Round Dial2.jpg', 'img/Women/IMPERIOUS - THE ROYAL WAY Women\'s Round Dial3.jpg', 'img/Women/IMPERIOUS - THE ROYAL WAY Women\'s Round Dial4.jpg', 55, 'Women', 'IMPERIOUS', '| Analogue Quartz Movement Ladies Watch', 'Stainless Steel Bracelet: Adjustable chain strap made of durable stainless steel for a comfortable and secure fit.\r\nPerfect Dimensions: Case thickness of 8mm, case diameter of 34mm, strap width of 15mm, and strap length of 210mm for an ideal fit.\r\nVersatile Style: Suitable for both casual and formal occasions, making it a versatile addition to your accessory collection.', '{\"Case diameter\":\"Case diameter\",\"Band colour\":\"Silver\",\"Band material type\":\"Metal\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"72 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-09 16:15:04', '2025-09-07 14:44:40'),
(39, 'Carlington Analog-Digital Sports Watch', 999.00, 'img/Children/Carlington Analog-Digital1.jpg', 'img/Children/Carlington Analog-Digital2.jpg', 'img/Children/Carlington Analog-Digital3.jpg', 'img/Children/Carlington Analog-Digital4.jpg', 50, 'Children', 'Carlington', ': Chronograph, Dual Time, Alarm, Stopwatch, Water-Resistant, Shock-Resistant, Back Light Display- The Perfect Watch for Men and Boys - CT3388', 'FUNCTIONALITY - This analog-digital watch features an alarm function, backlit display, calendar display, chronograph, stopwatch, and convenient buttons for start, reset, mode, and light. It ensures you stay on schedule, even in low-light conditions, and provides accurate timing for various activities. Its functional design makes it suitable for everyday wear and outdoor adventures.\r\nMEASUREMENTS - This analog-digital watch with a 55 mm diameter, protected by scratch-resistant mineral glass. It weighs around 67 g and has a 3-hand analog quartz movement. The strap length is 135 mm which provides a comfortable fit for everyday wear.', '{\"Case diameter\":\"55 Millimetres\",\"Band colour\":\"Blue\",\"Band material type\":\"Resin\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"0.08 Kilograms\",\"Country of Origin\":\"Hong Kong\"}', 'active', 'no', '2025-09-08 12:25:17', '2025-09-08 17:55:17'),
(40, 'Carlington Kids Digital Watch for Boys and Girls', 999.00, 'img/Children/Carlington Kids Digital1.jpg', 'img/Children/Carlington Kids Digital2.jpg', 'img/Children/Carlington Kids Digital3.jpg', 'img/Children/Carlington Kids Digital4.jpg', 45, 'Children', 'Carlington', 'Age 2 to 14 Years Pink Green Black Colour Band with Alarm and Date Display - CT_717\r\n', 'BRIGHT AND COLORFUL DESIGN: Engage your child with a vibrant and visually appealing digital watch. Made from non-toxic and hypoallergenic material.\r\nEASY-TO-READ DATE DISPLAY: Foster time-telling skills and help with scheduling activities.\r\nDURABLE AND COMFORTABLE: Made with high-quality material for long-lasting wear and comfort. Child-proof clasps to prevent accidental removal.', '{\"Case diameter\":\"45 Millimetres\",\"Band colour\":\"Black\",\"Band material type\":\"Silicone\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"42 Grams\",\"Country of Origin\":\"Hong Kong\"}', 'active', 'no', '2025-09-08 12:39:21', '2025-09-08 18:09:21'),
(41, 'Carlington Resin Analog-Digital Sports Watch Chronograph', 1399.00, 'img/Children/Carlington Resin Analog1.jpg', 'img/Children/Carlington Resin Analog2.jpg', 'img/Children/Carlington Resin Analog3.jpg', 'img/Children/Carlington Resin Analog4.jpg', 50, 'Children', 'Carlington', ',Dual Time,Alarm,Stopwatch,Water-Resistant,Shock-Resistant,Back Light Display- The Perfect Watch for Men&Boys-CT 9107 Series', 'DURABILITY - Designed with a rugged exterior, this watch is built to withstand the challenges of an active lifestyle. Its shock-resistant construction ensures it can endure accidental impacts and rough handling. The water-resistant feature adds an extra layer of protection, allowing you to wear it confidently even in wet conditions or during water-related activities.\r\nFUNCTIONALITY - This analog-digital watch features an alarm function, backlit display, calendar display, chronograph, stopwatch, and convenient buttons for start, reset, mode, and light. It ensures you stay on schedule, even in low-light conditions, and provides accurate timing for various activities. Its functional design makes it suitable for everyday wear and outdoor adventures.', '{\"Case diameter\":\"57 Millimetres\",\"Band colour\":\"Metallic\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"180 Grams\",\"Country of Origin\":\"Hong Kong\"}', 'active', 'no', '2025-09-08 12:51:38', '2025-09-08 18:21:38'),
(42, 'V2A Analog Digital Waterproof Fashion Sports Watch', 1090.00, 'img/Children/V2A Analog Digital1.jpg', 'img/Children/V2A Analog Digital2.jpg', 'img/Children/V2A Analog Digital3.jpg', 'img/Children/V2A Analog Digital4.jpg', 56, 'Children', 'V2A', 'with Backlight Alarm Stopwatch for Women and Girls', 'Fashion Sports Watch: Featuring fashionable design with large Dial, this Digital Analog sports suits Females of All Ages. Grab this watch for The Day, Work, Traveling, Shopping, Hanging Out, Walking or Just to Relax In. Pair It with Any Type of Outfit from Casual to Sporty and Everywhere In Between. Wrist Size: 15 cm – 21 cm\r\nWide Application: Men of All Ages Can Wear This Watch! Grab for The Day, Work, Traveling, Shopping, Hanging Out, Walking or Just to Relax In. Pair It with Any Type of Outfit from Casual to Sporty and Everywhere In Between. Wrist Size: 16.5 cm – 26.5 cm', '{\"Case diameter \":\"41 Millimetres \",\"Band colour\":\"Gray\",\"Band material type\":\"Resin\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"40 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-08 13:06:27', '2025-09-08 18:36:27'),
(43, 'V2A Cute Analog Design Watch for Girl -Child Between 4 to 13 Years of Age', 699.00, 'img/Children/V2A Cute Analog1.jpg', 'img/Children/V2A Cute Analog2.jpg', 'img/Children/V2A Cute Analog3.jpg', 'img/Children/V2A Cute Analog4.jpg', 55, 'Children', 'V2A', ' Square Printed Dial with Pink Band 30 M Waterproof Watches for Kids Aged 4 5 6 7 8 9, Pink Band', 'UNIQUE DESIGN: This unique design colourful watch is designed for kids aged 4-13 years of age. Kids look more vigorous, happy, and lovely when they wear the cute watches on wrist. Children will love this watch, which is really the best gifts for boys and girls aged 4 5 6 7 8 9 10 11.\r\nSAFE & COMFORTABLE:The watch strap is made of high-quality resin material for long-lasting durability while keeping your child\'s skin friendly. In addition, the adjustable strap with stainless steel strap buckle ensures customization and comfort, making kids play and exercise without restraint, suitable for any outdoor activities.', '{\"Case diameter\":\"38 Millimetres\",\"Band colour\":\"Black\",\"Band material type\":\"Resin\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Case thickness\":\"9.5 Millimetres\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-08 13:15:26', '2025-09-08 18:45:26'),
(44, 'V2A Boys and Girls Kids Watch - Waterproof Watch, Gifts for Boys and Girls Age 5-13', 599.00, 'img/Children/V2A Boys and Girls1.jpg', 'img/Children/V2A Boys and Girls2.jpg', 'img/Children/V2A Boys and Girls3.jpg', 'img/Children/V2A Boys and Girls4.jpg', 54, 'Children', 'V2A ', ' for Multi-Functional 30 M Waterproof Digital Sports Watches for 3 4 5 6 7 Year Old Girls', 'UNIQUE DESIGN: This kids watch is designed for 5-13 years old boys and girls. Kids look more vigorous, happy, and lovely when they wear the cute watches on wrist. Children will definitely love this watch, which is really the best gifts for boys and girls age 4 5 6 7 8 9 10 11.\r\nSAFE & COMFORTABLE: The watch strap is made of high-quality resin material for long-lasting durability while keeping your child\'s skin friendly. In addition, the adjustable strap with stainless steel strap buckle ensures customization and comfort, making kids play and exercise without restraint, suitable for any outdoor activities.', '{\"Case diameter\":\"38 Millimetres\",\"Band colour\":\"Multicolor\",\"Band material type\":\"Resin\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"80 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-21 09:07:08', '2025-09-08 18:57:31'),
(45, 'V2A Kids 3D Astronaut Print Digital Watch for Boys & Girls Aged 3 to 10', 799.00, 'img/Children/V2A Kids 3D Astronaut1.jpg', 'img/Children/V2A Kids 3D Astronaut2.jpg', 'img/Children/V2A Kids 3D Astronaut3.jpg', 'img/Children/V2A Kids 3D Astronaut4.jpg', 54, 'Children', 'V2A  ', '– Soft Silicone Strap | Multi-Function | Multicolour LED Luminous | Alarm Stopwatch Wristwatch | Gift for Kids Aged 3-10 Years!', '🛡 Safe & Skin-Friendly Materials – Crafted from lead & BPA-free, hypoallergenic PVC, this watch is gentle on delicate skin and completely free from harmful substances. Designed with child safety as a priority, it ensures all-day comfort without irritation, making it perfect for young, sensitive skin.\r\n🏫 School-Friendly Silent Mode – Designed for classrooms! This watch operates silently with no beep sounds while using any function, ensuring no distractions during school hours.\r\n⚡ Reliable Performance – Japanese Movement & Long Battery Life- Powered by Japanese movement and a high-quality Japanese battery, this watch ensures precise timekeeping a long battery life, so kids can enjoy it for years!', '{\"Case diameter \":\"34 Millimetres \",\"Band colour\":\"Black\",\"Band material type\":\"Silicone\",\"Warranty type\":\"Limited\",\"Watch movement type \":\"Quartz \",\"Item weight\":\"25 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-21 09:07:08', '2025-09-08 19:05:30'),
(46, 'YouBella Pocket Watch Pendant with Chain', 375.00, 'img/Antique/youbella_pocket_watch_pendant.jpg', 'img/Antique/youbella_packet_watch_pendant1.jpg', 'img/Antique/youbella_pocket_watch_pendant2.jpg', 'img/Antique/youbella_pocket_watch_pendant3.jpg', 57, 'Antique', 'YouBella', 'for Husband Unique Memorable Gift Dual Purpose Stainless Steel Clock for Men (YBWATCH_0030)', '', '{\"Item width\":\"50 Millimeters\",\"Material\":\"Non-Precious Metal\",\"Metal type\":\"Stainless Steel\",\"Clasp \":\"Tang\",\"type\":\"Buckle\",\"Metal weight\":\"50 g\",\"Gem type\":\"No Gemstone\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-25 03:00:54', '2025-09-16 17:10:25'),
(47, 'NORVILLE Antique Brass Analog Table Clock Vintage Glass Clock Watch ', 1149.00, 'img/Antique/NORVILLE Antique Brass.jpg', 'img/Antique/NORVILLE Antique Brass1.jpg', 'img/Antique/NORVILLE Antique Brass2.jpg', 'img/Antique/NORVILLE Antique Brass3.jpg', 57, 'Antique', 'NORVILLE ', 'for Study Table, Decor, Office Desk, Home Decor, Wedding Gift Item,3.81 cm', '', '{\"Brand \":\"NORVILLE \",\"Colour\":\"Golden\",\"Display Type\":\"Analog\",\"Style \":\"Modern \",\"Special Feature \":\"Silent Clock \",\"Product Dimensions\":\"6.5W x 24H Centimeters\",\"Power Source\":\"Battery Powered\",\"Age Range (Description)\":\"Adult\",\"Room Type\":\"Home Office\",\"Shape\":\"Round \"}', 'active', 'no', '2025-09-16 12:13:44', '2025-09-16 17:43:44');
INSERT INTO `products` (`id`, `name`, `price`, `img1`, `img2`, `img3`, `img4`, `quentity`, `category`, `brand_name`, `short_dec`, `long_dec`, `speci`, `status`, `trends`, `created_at`, `updated_at`) VALUES
(48, 'NORVILLE Antique Brass Analog Table Clock Vintage Glass Clock Watch', 879.00, 'img/Antique/NORVILLE Antique Brass Analog Table.jpg', 'img/Antique/NORVILLE Antique Brass Analog Table1.jpg', 'img/Antique/NORVILLE Antique Brass Analog Table2.jpg', 'img/Antique/NORVILLE Antique Brass Analog Table3.jpg', 55, 'Antique', 'NORVILLE ', 'For Study Table, Decoration, Office Desk, Home Decor, Wedding Gift Item, 6.4 Cm X 6.4 Cm', 'it is a watches is under stand disha suchak yantr', '{\"Brand  \":\"NORVILLE  \",\"Colour \":\"Golden \",\"Display Type\":\"Analog \",\"Style\":\"Art Deco\",\"Special Feature\":\"Silent Clock or\",\"Product Dimensions\":\"6.4W x 12H Centimeters\",\"Power Source\":\"Battery Powered\",\"Age Range (Description)\":\"Adult\",\"Room Type\":\"ANY ROOM\",\"Shape\":\"AS SHOWN IN PHOTOS\"}', 'active', 'no', '2025-09-16 12:21:46', '2025-09-16 17:51:46'),
(49, 'Zibuyu Pocket Watch For Men Antique Retro Style Alloy Classic Men Pocket Chain ', 558.00, 'img/Antique/Zibuyu Pocket Watch.jpg', 'img/Antique/Zibuyu Pocket Watch1.jpg', 'img/Antique/Zibuyu Pocket Watch2.jpg', 'img/Antique/Zibuyu Pocket Watch3.jpg', 56, 'Antique', 'Zibuyu', 'Analog Watch Special Birthday Gift For Husband, Frinds & Family Diameter (04.6 Cm) - Golden', '', '{\"Case diameter       \":\"4.6\",\"Band colour           \":\"Gold\",\"Band material type               \":\"Stainless Steel\",\"Watch movement type \":\"Quartz\",\"Item weight \":\"53.5 Grams\",\"Case thickness             \":\"10 Millimetres\",\"Country of Origin           \":\" China\"}', 'active', 'no', '2025-09-16 12:29:14', '2025-09-16 17:59:14'),
(50, 'Vintage Clock Double Side Analog Clock ', 1681.00, 'img/Antique/Vintage Clock Double Side.jpg', 'img/Antique/Vintage Clock Double Side1.jpg', 'img/Antique/Vintage Clock Double Side2.jpg', 'img/Antique/Vintage Clock Double Side3.jpg', 58, 'Antique', 'Vintage', 'With Brass Finish & 1 Year Warranty (6 Inches 15X15 Cm\'s Size)  (Railway Style)', '', '{\"Brand\":\"Vintage Clock\",\"Colour\":\"Shiny Gold\",\"Display Type\":\"Analog\",\"Style\":\"Vintage\",\"Special Feature\":\"clock\",\"Product Dimensions\":\"10W x 15H Centimeters\",\"Power Source\":\"Battery Powered\",\"Age Range (Description)\":\"Adult\",\"Room Type\":\"Office, Living Room gb, Guest Room\",\"Shape \":\"Round\"}', 'active', 'no', '2025-09-16 12:38:52', '2025-09-16 18:08:52'),
(51, 'NautiKraft Watch Brass with Wooden Tripod', 2999.00, 'img/Antique/Watch (Brass) with Wooden Tripod,jpg.jpg', 'img/Antique/Watch (Brass) with Wooden Tripod1.jpg', 'img/Antique/Watch (Brass) with Wooden Tripod2.jpg', 'img/Antique/Watch (Brass) with Wooden Tripod3.jpg', 45, 'Antique', 'NautiKraft', 'of Height of 47 inch for Floor of Living Room, Office, Floor Watch, Stand etc', '', '{\"Brand \":\"NautiKraft\",\"Colour\":\"Wooden and Brass\",\"Display Type\":\"Analog\",\"Style\":\"Antique\",\"Special Feature\":\"Foldable\",\"Product Dimensions\":\"30W x 117.5H Centimeters\",\"Power Source\":\"Battery Powered\",\"Room Type\":\"Office, Living Room, Hallway\",\"Shape\":\"Round\",\"Indoor\\/Outdoor Usage\":\"Indoor\"}', 'active', 'no', '2025-09-16 13:02:31', '2025-09-16 18:32:31'),
(52, 'Luxury Lion Curved Rose Gold Dial Bracelet Unisex Wrist Watch Analog Watch  for Men Antique', 1499.00, 'img/Antique/Luxury Lion Curved Rose Gold.jpg', 'img/Antique/Luxury Lion Curved Rose Gold1.jpg', 'img/Antique/Luxury Lion Curved Rose Gold2.jpg', 'img/Antique/Luxury Lion Curved Rose Gold3.jpg', 26, 'Antique', 'Luxury Lion ', '', '', '{\"Case diameter              \":\"24 Millimetres\",\"Band colour                        \":\"Black\",\"Band material type              \":\"Stainless Steel\",\"Watch movement type         \":\"Automatic\",\"Item weight                  \":\"300 Grams\",\"Case thickness        \":\"10 Millimetres\",\"Country of Origin        \":\"India\"}', 'active', 'no', '2025-09-16 13:11:09', '2025-09-16 18:41:09'),
(53, 'Spiffy Eleganzza Women Watches Analogue Wrist Watches ', 399.00, 'img/Antique/Spiffy Eleganzza Women Watches.jpg', 'img/Antique/Spiffy Eleganzza Women Watches1.jpg', 'img/Antique/Spiffy Eleganzza Women Watches2.jpg', 'img/Antique/Spiffy Eleganzza Women Watches3.jpg', 56, 'Antique', 'Spiffy Eleganzza ', '', '', '{\"Case diameter                  \":\"36 Millimetres\",\"Band colour                        \":\" Brown\",\"Band material type              \":\"Leather\",\"Warranty type       \":\"Limited\",\"Watch movement type       \":\"Japanese Quartz\",\"Item weight         \":\"80 Grams\",\"Country of Origin          \":\"China\"}', 'active', 'no', '2025-09-16 13:18:05', '2025-09-16 18:48:05'),
(54, 'Auromin Antique Metal Wall Clock for Hall Big Size ', 1529.00, 'img/Wall/Auromin Antique Metal Wall Clock.jpg', 'img/Wall/Auromin Antique Metal Wall Clock1.jpg', 'img/Wall/Auromin Antique Metal Wall Clock2.jpg', 'img/Wall/Auromin Antique Metal Wall Clock3.jpg', 50, 'Wall', 'Auromin', '| Modern Decorative Clocks for Living Room Stylish | Designer Wall Watch for Bedroom, Office, Drawing Room, Kitchen, Cafe/Restaurant', '', '{\"Brand\":\"AUROMIN ; THE ART OF INGENUITY\",\"Colour\":\"Multicolour\",\"Display Type\":\"Analog\",\"Style\":\"Modern\",\"Special Feature\":\"Silent Sweep Mechanism, Durability, Size Variety, Wall Mountable, Easy to Hang\",\"Product Dimensions\":\"50W x 50H Centimeters\",\"Power Source\":\"Battery Powered\",\"Age Range (Description)\":\"Adult\",\"Room Type\":\"Dinning Room, Living Room, Bedroom, Study Room, Drawing Room\",\"Shape\":\"Hexagonal\"}', 'active', 'no', '2025-09-26 12:39:45', '2025-09-17 18:41:33'),
(55, 'Umi Moving Gear Wall Clock for Living Room Modern Plastic Wall Clocks', 1299.00, 'img/Wall/Amazon Brand - Umi Moving Gear Wall Clock.jpg', 'img/Wall/Amazon Brand - Umi Moving Gear Wall Clock1.jpg', 'img/Wall/Amazon Brand - Umi Moving Gear Wall Clock2.jpg', 'img/Wall/Amazon Brand - Umi Moving Gear Wall Clock3.jpg', 55, 'Wall', 'Umi', 'Industrial Steampunk Moving Gear Analog Wall Clock for Home Decor Office (32.5cm Diameter Clock) (Silver Black)', '', '{\"Brand\":\"Amazon Brand - Umi\",\"Colour\":\"Silver Black\",\"Display Type\":\"Analog\",\"Style\":\"Modern\",\"Special Feature\":\"Real Moving Gears, Large Display, Round Shape, Light Weight And Easy To Hang\",\"Product \":\"32.5W x 32.5H \",\"Dimensions\":\"Centimeters\",\"Power Source\":\"Battery Powered\",\"Room Type\":\"Office, Living Room, Bedroom, Hallway, Hotel\",\"Shape\":\"Round\",\"Indoor\\/Outdoor Usage\":\"Indoor\"}', 'active', 'yes', '2025-09-26 12:39:45', '2025-09-17 18:48:57'),
(56, 'Craft2lance Metal Analog Wall Clock Decor Art Sculpture ', 1799.00, 'img/Wall/Craft2lance Metal Analog Wall Clock.jpg', 'img/Wall/Craft2lance Metal Analog Wall Clock1.jpg', 'img/Wall/Craft2lance Metal Analog Wall Clock2.jpg', 'img/Wall/Craft2lance Metal Analog Wall Clock3.jpg', 57, 'Wall', 'Craft2lance', 'For Home Office Living Room Bedroom Restaurant Cafe (24 Inches/ 60 Cms),Multicolour', '', '{\"Brand\":\"Craft2lance\",\"Colour\":\"Multicolour\",\"Display Type\":\"Analog\",\"Style\":\"Art Deco\",\"Special Feature\":\"Silent Clock\",\"Product Dimensions\":\"40W x 60H Centimeters\",\"Power Source\":\"Battery Powered\",\"Room Type\":\"Living Room, Bedroom, Home Office, Study Room, Dining Room\",\"Indoor\\/Outdoor Usage\":\"Indoor\",\"Material\":\"Metal\"}', 'active', 'no', '2025-09-26 12:39:45', '2025-09-17 18:55:49'),
(57, 'AVVIC MART Stylish Metal Analog Wall Clock ', 1299.00, 'img/Wall/AVVIC MART Stylish Metal Analog Wall Clock.jpg', 'img/Wall/AVVIC MART Stylish Metal Analog Wall Clock1.jpg', 'img/Wall/AVVIC MART Stylish Metal Analog Wall Clock2.jpg', 'img/Wall/AVVIC MART Stylish Metal Analog Wall Clock3.jpg', 56, 'Wall', 'AVVIC MART', 'for Living Room, Bedroom, Office, Kitchen, Home and Hall | Antique Fancy Big Size Modern Wall Watch for Home Decor (Style-31, 40CM)', '', '{\"Brand\":\"AVVIC MART\",\"Colour\":\"Style-31\",\"Display Type\":\"Analog\",\"Style\":\"Modern\",\"Special Feature\":\"Silent Clock\",\"Product Dimensions\":\"40W x 40H Centimeters\",\"Power Source\":\"Battery Powered\",\"Room Type\":\"Office, Bedroom, Living Room, Study Room\",\"Shape\":\"Round\",\"Indoor\\/Outdoor Usage\":\"Indoor\"}', 'active', 'no', '2025-09-26 12:39:45', '2025-09-17 19:01:58'),
(58, 'Babawill Near Sea Night Abs Plastic Wall ', 798.00, 'img/Wall/Babawill Near Sea Night Abs.jpg', 'img/Wall/Babawill Near Sea Night Abs1.jpg', 'img/Wall/Babawill Near Sea Night Abs2.jpg', 'img/Wall/Babawill Near Sea Night Abs3.jpg', 45, 'Wall', 'Babawill', 'with Glass in Front 28 x 28 x 6 Cm', '', '{\"Brand \":\"Babawill\"}', 'active', 'no', '2025-09-26 12:39:45', '2025-09-17 19:05:27'),
(59, 'invision1 Plastic 3D Acrylic Tree Birds Coffee Cup On Jhula Design Wall Clock ', 960.00, 'img/Wall/invision1 Plastic 3D Acrylic Tree Birds.jpg', 'img/Wall/invision1 Plastic 3D Acrylic Tree Birds1.jpg', 'img/Wall/invision1 Plastic 3D Acrylic Tree Birds2.jpg', 'img/Wall/invision1 Plastic 3D Acrylic Tree Birds3.jpg', 45, 'Wall', 'invision1', '(Black, 69.9 x 41.9 x 1.3 cm) Analog', '', '{\"Brand\":\"invision1\",\"Colour\":\"Black\",\"Display Type\":\"Analog\",\"Style\":\"Modern\",\"Special Feature\":\"Silent Clock, Waterproof, Night Mode\",\"Power Source\":\"Battery Powered\",\"Age Range (Description)\":\"Adult\",\"Room Type\":\"Office, Living Room, Bedroom\",\"Shape\":\"Tree, Round\",\"Indoor\\/Outdoor Usage\":\"Indoor\"}', 'active', 'no', '2025-09-26 12:39:45', '2025-09-17 19:12:21'),
(60, 'Vintage of world Wall Clock for Home Stylish ', 2499.00, 'img/Wall/Vintage of world® Wall Clock.jpg', 'img/Wall/Vintage of world® Wall Clock1.jpg', 'img/Wall/Vintage of world® Wall Clock2.jpg', 'img/Wall/Vintage of world® Wall Clock3.jpg', 57, 'Wall', 'Vintage ', '20 inch dial 8 inch Black Colour Beautiful Flower Design Antique Style Art Unique Office Decor Iron Metal Glass (Style 2)', '', '{\"Brand\":\"Vintage of world\",\"Colour\":\"Style 2\",\"Display Type\":\"Analog\",\"Style\":\"Art Deco\",\"Special Feature\":\"Silent Clock\",\"Product Dimensions\":\"50W x 5H Centimeters\",\"Power Source\":\"Battery Powered\",\"Age Range (Description)\":\"Adult\",\"Room Type\":\"Home Office\",\"Shape\":\"Flower\"}', 'active', 'no', '2025-09-26 12:39:45', '2025-09-17 19:20:41'),
(61, 'Handcrafted Resin Art Wall Clock ', 2099.00, 'img/Wall/Handcrafted Resin Art Wall Clock.jpg', 'img/Wall/Handcrafted Resin Art Wall Clock1.jpg', 'img/Wall/Handcrafted Resin Art Wall Clock2.jpg', 'img/Wall/Handcrafted Resin Art Wall Clock3.jpg', 55, 'Wall', 'Generic', '– Unique Modern Abstract Design, Quality Verified, Decorative Clock for Living Room, Bedroom, Office & Home Décor (Design 16, 30cm x 30cm (Small 12inch))', '', '{\"Brand\":\"Generic\",\"Colour\":\"Design 16\",\"Display Type\":\"Analog\",\"Style\":\"Modern\",\"Special Feature\":\"Handmade resin clock\",\"Product Dimensions\":\"30W x 30H Centimeters\",\"Power Source\":\"Battery Powered\",\"Room Type\":\"Office, Living Room, Bedroom\",\"Shape\":\"Round\",\"Indoor\\/Outdoor Usage\":\"Indoor\"}', 'active', 'yes', '2025-09-26 12:39:45', '2025-09-17 19:27:38'),
(62, 'vissera Metal Modern Wall Clock for Living Room', 1234.00, 'img/Wall/vissera Metal Modern Wall Clock for Living Room.jpg', 'img/Wall/vissera Metal Modern Wall Clock for Living Room1.jpg', 'img/Wall/vissera Metal Modern Wall Clock for Living Room2.jpg', 'img/Wall/vissera Metal Modern Wall Clock for Living Room3.jpg', 43, 'Wall', 'vissera', ', Bedroom, Office, Hall | Non-Ticking Hanging Wall Clock for Wall Decoration | Antique Big Size Silent Wall Watch for Home Decor Items (40 CM)', '', '{\"Brand\":\"vissera\",\"Colour\":\"Black\",\"Display Type\":\"Analog\",\"Style\":\"Modern\",\"Special Feature\":\"Silent Sweep Mechanism, Durability\",\"Product Dimensions\":\"40W x 40H Centimeters\",\"Power Source\":\"Battery Powered\",\"Room Type\":\"Living Room\",\"Shape\":\"Round\",\"Indoor\\/Outdoor Usage\":\"Indoor\"}', 'active', 'no', '2025-09-26 12:39:45', '2025-09-17 19:33:26'),
(63, 'Shocknshop Analogue Mens & Womens Watch', 395.00, 'img/Couple/Shocknshop Analogue1.jpg', 'img/Couple/Shocknshop Analogue2.jpg', 'img/Couple/Shocknshop Analogue3.jpg', 'img/Couple/Shocknshop Analogue4.jpg', 50, 'Couple', 'Shocknshop', '(Pack Of 2, Brown Dial & Strap , Leather)', 'The product comes in Proper Packaging\r\nAdd a unique touch of individuality to your style statement by pairing this watch with any outfit of your choice\r\nThis is perfect for all occasions\r\nBezel Function: No Bezel Available; Dial Window Material Type: Mineral; Department Name: Unisex; Item Shape: Round', '{\"Band colour\":\"Brown\",\"Band material type\":\"Leather, Metal\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"100 Grams\",\"Band width\":\"22 Millimetres\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-24 16:18:07', '2025-09-18 17:52:51'),
(64, 'Shocknshop Leather Analogue Unisex Couple Combo Watch For Men & Women', 419.00, 'img/Couple/Shocknshop Leather Analogue1.jpg', 'img/Couple/Shocknshop Leather Analogue2.jpg', 'img/Couple/Shocknshop Leather Analogue3.jpg', 'img/Couple/Shocknshop Leather Analogue4.jpg', 50, 'Couple', 'Shocknshop', '(Brown Dial & Colored Strap) -W246-236Br, Brown Band)', 'Dial Color: Brown; Dial Material: Copper\r\nDial Shape: Round; Strap Color: Brown\r\nStrap Material: Leather\r\nWatch Movement Type: Quartz\r\nModel number: W246-236BR', '{\"Band colour \":\"Brown \",\"Case diameter\":\"46 Millimetres\",\"Band material type\":\"Leather, Metal\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"100 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-24 16:18:07', '2025-09-18 18:02:02'),
(65, 'Shocknshop Leather Analogue Unisex Couple Combo Watch For Men & Women', 495.00, 'img/Couple/Shocknshop Leather Analogue Unisex1.jpg', 'img/Couple/Shocknshop Leather Analogue Unisex2.jpg', 'img/Couple/Shocknshop Leather Analogue Unisex3.jpg', 'img/Couple/Shocknshop Leather Analogue Unisex4.jpg', 50, 'Couple', 'Shocknshop', ' (White Dial & Brown Colored Strap) -Lr94-341, Brown Band\r\n', 'White Dial Japanese Quartz Movement. Watches For Mens & Womens\r\nBand Color:Brown, Band Material: Genuine Leather\r\nSuitable for Casual wear, formal wear.Partywear\r\nStylish Look || Make in India Product\r\nHigh quality Leather used for your desire look', '{\"Case diameter\":\"50 Millimetres\",\"Band colour\":\"Brown\",\"Band material type\":\"Leather\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"100 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-24 16:18:07', '2025-09-18 18:09:46'),
(66, 'jainx Premium Golden Analog Wrist Watch for Couple - JC441', 913.00, 'img/Couple/jainx Premium Golden1.jpg', 'img/Couple/jainx Premium Golden2.jpg', 'img/Couple/jainx Premium Golden3.jpg', 'img/Couple/jainx Premium Golden4.jpg', 50, 'Couple', 'jainx', '', 'Dial Color - White, Dial Material - Metal, Dial Shape - Round\r\nSuitable for Party Wedding, Formal and Casual Occasion\r\nBand Color -Multicolour, Band Material -Stainless Steel Gold Plated\r\nWatch Movement Type - Quartz, Model - JC441\r\nWarranty Type - Manufacturer, 6 Months Warranty', '{\"Band colour\":\"Multicolor\",\"Band material type\":\"Stainless Steel Gold Plated\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"250 Grams\",\"Band width\":\"22 Millimetres\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-24 16:18:07', '2025-09-18 18:18:16'),
(67, 'jainx Multi Color Dial Analog Watch for Couple ', 469.00, 'img/Couple/jainx Multi Color1.jpg', 'img/Couple/jainx Multi Color2.jpg', 'img/Couple/jainx Multi Color3.jpg', 'img/Couple/jainx Multi Color4.jpg', 55, 'Couple', 'jainx', '(Pack of 2)', 'Dial Color - Multicolour, Dial Material - Metal, Dial Shape - Round\r\nSuitable for Party Wedding, Formal and Casual Occasion\r\nBand Color -Blue, Band Material -Leather\r\nWatch Movement Type - Quartz, Model - JC439\r\nWarranty Type - Manufacturer, 6 Months Warranty', '{\"Case diameter\":\"44 Millimetres\",\"Band colour\":\"Blue\",\"Band material type\":\"Leather\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Case thickness\":\"10 Millimetres\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-24 16:18:07', '2025-09-18 18:27:38'),
(68, 'jainx Blue Dial Steel Chain Gift Set Analog Wrist Watch for Couple', 599.00, 'img/Couple/jainx Blue Dial Steel1.jpg', 'img/Couple/jainx Blue Dial Steel2.jpg', 'img/Couple/jainx Blue Dial Steel3.jpg', 'img/Couple/jainx Blue Dial Steel4.jpg', 55, 'Couple', 'jainx', '- JC9404', 'Dial Color - Blue, Dial Material - Metal, Dial Shape - Round\r\nSuitable for Party Wedding, Formal and Casual Occasion\r\nBand Color -Silver, Band Material -Stainless Steel\r\nWatch Movement Type - Quartz, Model - JC9404\r\nWarranty Type - Manufacturer, 6 Months Warranty', '{\"Case diameter\":\"44 Millimetres\",\"Band colour\":\"Silver\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"item weight\":\"180 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-24 16:18:07', '2025-09-18 18:34:24'),
(69, 'jainx Day and Date Dial Steel Chain Analog Wrist Watch for Couple', 659.00, 'img/Couple/jainx Day and Date1.jpg', 'img/Couple/jainx Day and Date2.jpg', 'img/Couple/jainx Day and Date3.jpg', 'img/Couple/jainx Day and Date4.jpg', 56, 'Couple', 'jainx', '(Black/Silver/Red/Blue Dial)', 'Dial Color - Blue, Dial Material - Metal, Dial Shape - Round\r\nDial Feature - Day & Date\r\nBand Color -Silver, Band Material -Stainless Steel\r\nWatch Movement Type - Quartz, Model - JC479\r\nWarranty Type - Manufacturer, 6 Months Warranty', '{\"Case diameter\":\"44 Millimetres\",\"Band colour\":\"Silver\",\"Band material type\":\"Stainless Steel\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Case thickness\":\"10 Millimetres\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-24 16:18:07', '2025-09-18 19:00:01'),
(70, 'jainx Multicolor Silicone Band Men and Women Analog Watch', 549.00, 'img/Couple/jainx Multicolor Silicone1.jpg', 'img/Couple/jainx Multicolor Silicone2.jpg', 'img/Couple/jainx Multicolor Silicone3.jpg', 'img/Couple/jainx Multicolor Silicone4.jpg', 58, 'Couple', 'jainx', '- for Couple JC9406', 'Dial Color - Multi-Color, Dial Material - Metal, Dial Shape - Round\r\nSuitable for Party Wedding, Formal and Casual Occasion\r\nBand Color -Grey, Band Material -Silicone\r\nWatch Movement Type - Quartz, Model - JC9406\r\nWarranty Type - Manufacturer, 6 Months Warranty', '{\"Case diameter\":\"44 Millimetres\",\"Band colour\":\"Gray\",\"Band material type\":\"Silicone\",\"Warranty type\":\"Manufacturer\",\"Watch movement type\":\"Quartz\",\"Item weight\":\"180 Grams\",\"Country of Origin\":\"India\"}', 'active', 'no', '2025-09-27 06:03:33', '2025-09-18 19:08:12');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `user_id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('user','admin') NOT NULL DEFAULT 'user',
  `phone` varchar(15) NOT NULL,
  `address` text NOT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `pin` int(10) NOT NULL,
  `city` varchar(100) NOT NULL,
  `stat` varchar(100) NOT NULL DEFAULT 'Gujrat ',
  `country` enum('india') NOT NULL DEFAULT 'india'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`user_id`, `name`, `email`, `password`, `role`, `phone`, `address`, `status`, `created_at`, `pin`, `city`, `stat`, `country`) VALUES
(1, 'Dhrudip Timbaliya', 'dhrudip@gmail.com', 'dhrudip2005', 'admin', '9328070359', 'aadarsh avnu ,mavdi', 'active', '2025-07-27 06:25:53', 360004, 'rajkot', 'gujrat', 'india'),
(2, 'keval limbasiya', 'keval@gmail.com', '635566', 'user', '6355669169', ';ksqjfpojewfrqwoefhq3othuofhqwth1uot', 'active', '2025-07-27 06:30:08', 36004, 'qwdjlhduo', 'Gujrat', 'india'),
(5, 'zeel timbaliya', 'zeel@gmail.com', '159263', 'admin', '94554544454', 'MAVDI PLOT, NEAR UMAKANT INDUSTRIAL AREA, NEAR\r\nMOMAI INDUSTRIES, STREET NO 05, AMARNAGAR-2, RAJKO\r\nAMARNAGAR RAJKOT', 'active', '2025-07-27 16:38:48', 0, '', 'Gujrat ', 'india'),
(6, 'akshay adani', 'akshay@gmail.com', '123456', 'user', '7894561230', 'mavdi,rajkot', 'active', '2025-07-27 16:44:28', 0, '', 'Gujrat ', 'india'),
(7, 'abhi baraiya', 'abhi@gmail.com', 'abhi1234', 'user', '3216549870', 'mavadi ,rajkot', 'active', '2025-07-27 16:51:11', 0, '', 'Gujrat ', 'india'),
(10, 'dhruvik baraiya', 'dhruvik@gmail.com', '147258369', 'user', '753421689', 'mavdi,rajkot', 'active', '2025-07-27 16:54:39', 0, '', 'Gujrat ', 'india'),
(13, 'meet', 'hashmukh@gmail.com', '123456', 'user', '09727480282', 'radhesyam mavdimain road .', 'inactive', '2025-08-22 13:56:33', 360004, 'rajkot', 'gujrat', 'india'),
(14, 'dddd wwww', 'abc@gmail.com', '123', 'user', '57557457477', 'sdfgfdgfbg', 'active', '2025-09-25 06:37:41', 534345, 'fsdfsdgdfg', 'dsfd', 'india');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `crousel`
--
ALTER TABLE `crousel`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `feed`
--
ALTER TABLE `feed`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`order_id`),
  ADD KEY `user_id` (`user_id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`user_id`),
  ADD UNIQUE KEY `email` (`email`),
  ADD UNIQUE KEY `phone` (`phone`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

--
-- AUTO_INCREMENT for table `crousel`
--
ALTER TABLE `crousel`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- AUTO_INCREMENT for table `feed`
--
ALTER TABLE `feed`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `orders`
--
ALTER TABLE `orders`
  MODIFY `order_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(150) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=73;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `orders`
--
ALTER TABLE `orders`
  ADD CONSTRAINT `user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
